#!/bin/sh

## A quick hack to deploy a generated website onto a Github repository, to be served as static content by github pages.

# This should only be run from the root of the gitbook project

# Trigger a clean and new build
gitbook build .

# Prevent Jekyll processing when pushing commits to GitHub
touch _book/.nojekyll

# Add Practicalli favicon
cp -f images/favicon_io/favicon.ico _book/gitbook/images/favicon.ico

# Add Apple touch icon
cp -f images/favicon_io/apple-touch-icon.png _book/gitbook/images/apple-touch-icon-precomposed-152.png


# Deploy new build
cd _book && git init && git add . && git commit -m "Publish new version of Practicalli Clojure book" && git remote add practicalli git@github.com:jr0cket/clojure-new-theme.git && git push -f practicalli live
