#!/bin/sh

## A quick hack to deploy a generated website onto a Github repository, to be served as static content by github pages.  This is an example of a very bad shell script.

# This should only be run from the root of the gitbook project
# Replace the remote Github URL to use this on a different project
rm -rf _book

# Trigger a clean and new build
gitbook build .

# Prevent Jekyll processing when pushing commits to GitHub
touch _book/.nojekyll

# Deploy new build
cd _book && git init && git add . && git commit -m "automated commit from gitbook.io" && git branch -m master gh-pages && git remote add practicalli git@github.com:practicalli/clojure.git && git push -f practicalli gh-pages
